---
- name: Installer les dépendances de base
  ansible.builtin.apt:
    name:
      - git
      - curl
      - wget
      - ca-certificates
      - gnupg
      - sudo
      - jq
      - net-tools
      - lsof
      - strace
      - tcpdump
    state: present
    update_cache: yes

- name: Inclure le socle Docker (installation + user docker-admin)
  ansible.builtin.include_role:
    name: docker_base

- name: Vérifier Docker avec BusyBox (userns=host)
  ansible.builtin.command: docker run --rm --userns=host busybox echo "Docker fonctionne !"
  register: docker_test
  changed_when: false
  ignore_errors: yes
