---
all:
  vars:
    secrets: "{{ lookup('file', '~/projects/home-lab/.env.json') | from_json }}"

  children:
    proxmox_ryzen:
      hosts:
        pve-ryzen:
          ansible_host: "{{ secrets.pve_host_ryzen }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab

    lxc_storage:
      hosts:
        lxc-storage:
          ansible_host: "{{ secrets.lxc_storage.ip | regex_replace('/24', '') }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab

    lxc_ai:
      hosts:
        ai-node:
          ansible_host: "{{ secrets.ai_node.ip | regex_replace('/24', '') }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab

    lxc_devstation_nuc:
      hosts:
        dev-station-nuc:
          ansible_host: "{{ secrets.dev_station_nuc.ip | regex_replace('/24', '') }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab

    lxc_devstation_ryzen:
      hosts:
        dev-station-ryzen:
          ansible_host: "{{ secrets.dev_station_ryzen.ip | regex_replace('/24', '') }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab

    lxc_apps_runner_ryzen:
      hosts:
        apps-runner-ryzen:
          ansible_host: "{{ secrets.apps_runner_ryzen.ip | regex_replace('/24', '') }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab

    lxc_ha_runner_ryzen:
      hosts:
        ha-runner-ryzen:
          ansible_host: "{{ secrets.ha_runner_ryzen.ip | regex_replace('/24', '') }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab

    lxc_apps2_runner_ryzen:
      hosts:
        apps2-runner-ryzen:
          ansible_host: "{{ secrets.apps2_runner_ryzen.ip | regex_replace('/24', '') }}"
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab
