---
- name: Configuration de Samba sur le Storage Server
  hosts: storage_servers
  gather_facts: yes
  tasks:
    - name: Installation de Samba
      apt:
        name: samba
        state: present
        update_cache: yes

    - name: Création du répertoire de montage (si absent)
      file:
        path: /mnt/public_data
        state: directory
        mode: '0775'

    - name: Configuration du partage PublicData
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [PublicData]
             path = /mnt/public_data
             browseable = yes
             read only = no
             guest ok = yes
             force user = root
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Redémarrage de Samba
      service:
        name: smbd
        state: restarted
        enabled: yes